version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"

  www:
    build: ./docker/php
    volumes:
      - "./:/var/www/html"
    ports:
      - 3000:80
      - 443:443

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 5432:80
    environment:
      - PMA_HOST=${PMA_HOST}         # The host is loaded from .env
      - PMA_PORT=${PMA_PORT}         # The port is loaded from .env
      - PMA_USER=${PMA_USER}         # The user is loaded from .env
      - PMA_PASSWORD=${PMA_PASSWORD} # The password is loaded from .env